#!/usr/local/bin/python3

import sys

def main():
    arguments = sys.argv
    arguments.pop(0)
    
    if len(arguments) == 0:
        print_usage_message()
        return 1
    
    if "-h" in arguments or "--help" in arguments:
        print_usage_message()
        return 0

    first_argument = arguments[0]
    try:
        episode_number = int(first_argument)
    except ValueError:
        print("You did not enter a proper episode number.")
        return 1

    print(f"Episode number: {first_argument}")

def print_usage_message():
    with open("usage_message.txt", 'r') as f:
        print(f.read())

if __name__ == "__main__":
    sys.exit(main())
