#!/usr/bin/env bash

# assumes that setup is run as
# $ ./setup
# instead of as
# $ DynamicJRE/setup

echo "--------------------"

echo "Creating symbolic link"
ln -s "$(pwd)/jrep.py" "/usr/local/bin/jrep"
echo ""

echo "Creating settings file"
touch settings.txt
echo ""

echo "Setup complete."

echo "--------------------"  
